#!/bin/bash
sudo apt -y update
sudo apt -y upgrade

#install node.js
sudo apt install -y nodejs npm build-essential curl software-properties-common graphicsmagick vim wget

sudo npm install -g inherits n
sudo n 12.16.1

#install mongo
#=====================
sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 9DA31620334BD75D9DCB49F368818C72E52529D4
sudo add-apt-repository 'deb [arch=amd64] https://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/4.0 multiverse'

sudo apt -y update
sudo apt -y install mongodb-org

sudo systemctl start mongod
sudo systemctl enable mongod

sudo echo -e "replication:\n replSetName: \"rs01\"" | tee -a /etc/mongod.conf
sudo systemctl restart mongod
sudo mongo --eval "rs.initiate()"

#create rocket user and home dir
sudo useradd -m -U -r -d /opt/rocket rocket

sudo usermod -a -G rocket www-data
sudo chmod 750 /opt/rocket
#download rocketchat and install with npm
sudo -u rocket cd /opt/rocket
sudo -u rocket curl -L https://releases.rocket.chat/latest/download -o rocket.chat.tgz
sudo -u rocket tar zxf rocket.chat.tgz
sudo -u rocket mv bundle Rocket.Chat
sudo -u rocket cd Rocket.Chat/programs/server
sudo -u rocket npm install
#set enviro variables
sudo -u rocket export ROOT_URL=http://192.168.1.176:3000
sudo -u rocket export MONGO_URL=mongodb://localhost:27017/rocketchat
sudo -u rocket export MONGO_OPLOG_URL=mongodb://localhost:27017/local?replSet=rs01
sudo -u rocket export PORT=3000
#check node to be working proper
sudo -u rocket cd /opt/rocket/Rocket.Chat
sudo -u rocket node main.js

#create the rocketchat sys service
if [[ -f /etc/systemd/system/rocketchat.service ]]; then
	sudo echo ">>>>rocketchat.service file already exists!"
	sudo echo ">>>>Skipping config of the rocketchat sys service!"
else
	sudo touch /etc/systemd/system/rocketchat.service
	sudo echo "[Unit]" >> /etc/systemd/system/rocketchat.service
	sudo echo "Description=Rocket.Chat server" >> /etc/systemd/system/rocketchat.service
	sudo echo "After=network.target nss-lookup.target mongod.target" >> /etc/systemd/system/rocketchat.service
	sudo echo "[Service]" >> /etc/systemd/system/rocketchat.service
	sudo echo "StandardOutput=syslog" >> /etc/systemd/system/rocketchat.service
	sudo echo "StandardError=syslog" >> /etc/systemd/system/rocketchat.service
	sudo echo "SyslogIdentifier=rocketchat" >> /etc/systemd/system/rocketchat.service
	sudo echo "User=rocketchat" >> /etc/systemd/system/rocketchat.service
	sudo echo "Environment=MONGO_URL=mongodb://localhost:27017/rocketchat MONGO_OPLOG_URL=mongodb://localhost:27017/local?replSet=rs01 ROOT_URL=http://192.168.1.176 PORT=3000" >> /etc/systemd/system/rocketchat.service
	sudo echo "ExecStart=/usr/local/bin/node /opt/rocketchat/Rocket.Chat/main.js" >> /etc/systemd/system/rocketchat.service
	sudo echo "[Install]" >> /etc/systemd/system/rocketchat.service
	sudo echo "WantedBy=multi-user.target" >> /etc/systemd/system/rocketchat.service
fi
#reload, enable, start rocketchat
sudo systemctl daemon-reload
sudo systemctl enable rocketchat
sudo systemctl start rocketchat
